/*
 * ORATOR exercise library.
 * Categories map to the trained skills; tiers map to difficulty.
 */

export const CATEGORIES_META = {
  organisation: { label: 'Thought organisation', skill: 'thoughtOrganisation' },
  precision: { label: 'Word precision', skill: 'wordPrecision' },
  fillers: { label: 'Anti-filler', skill: 'fluency' },
  pace: { label: 'Controlled pace', skill: 'vocalDelivery' },
  articulation: { label: 'Articulation', skill: 'articulation' },
  story: { label: 'Storytelling', skill: 'storytelling' },
  persuasion: { label: 'Persuasion', skill: 'persuasion' },
  pressure: { label: 'Speaking under pressure', skill: 'underPressure' },
  explain: { label: 'Explaining ideas', skill: 'explaining' },
  concise: { label: 'Conciseness', skill: 'conciseness' },
  opinion: { label: 'Opinion & defence', skill: 'responseSpeed' },
};

const T = { f: 1, d: 2, a: 3, e: 4 }; // foundation, developing, advanced, elite

export const EXERCISES = [
  /* ---- organisation ---- */
  { id: 'org1', category: 'organisation', tier: T.f, title: 'The Fixed Path', objective: 'Make every answer follow one visible path.', prompt: 'Why does clear structure make a speaker more persuasive?', instructions: ['Decide your single point before you begin.', 'Walk the listener through POINT → REASON → EXAMPLE → CONCLUSION.', 'Say the stage markers out loud.'], prepSeconds: 15, speakSeconds: 60 },
  { id: 'org2', category: 'organisation', tier: T.d, title: 'The Three Doors', objective: 'Organise an answer into exactly three parts.', prompt: 'Convince a sceptic that preparation matters more than talent.', instructions: ['Announce your three parts in the first sentence.', 'Deliver each part with a marker, then close.'], prepSeconds: 15, speakSeconds: 75 },
  { id: 'org3', category: 'organisation', tier: T.a, title: 'The Collapsing Argument', objective: 'Hold structure while the ground moves.', prompt: 'Defend this position: remote work weakens young careers. A listener will challenge you.', instructions: ['Keep POINT → REASON → EXAMPLE alive even as the position is attacked.', 'Never let the challenge pull you into rambling.'], prepSeconds: 10, speakSeconds: 60 },
  { id: 'org4', category: 'organisation', tier: T.e, title: 'Structure Without Signposts', objective: 'Sound organised without saying the markers.', prompt: 'Explain what separates a good decision from a defensible one.', instructions: ['The path must be invisible but felt.', 'Transitions should be earned by logic, not announced.'], prepSeconds: 5, speakSeconds: 90 },

  /* ---- precision ---- */
  { id: 'prec1', category: 'precision', tier: T.f, title: 'The Vague Ban', objective: 'Remove vague words from your working vocabulary.', prompt: 'Describe the best meal you have ever eaten without using "good", "nice", "amazing" or "delicious".', instructions: ['Every claim carries a specific quality.', 'If you notice a vague word, correct it out loud and continue.'], prepSeconds: 15, speakSeconds: 60 },
  { id: 'prec2', category: 'precision', tier: T.d, title: 'The Measurement', objective: 'Replace "a lot" with numbers and scale.', prompt: 'Convince someone that they underestimate how much time they lose to distractions. Use at least two numbers.', instructions: ['Numbers may be estimates, but they must be stated.', 'Vague quantity words are banned.'], prepSeconds: 15, speakSeconds: 60 },
  { id: 'prec3', category: 'precision', tier: T.a, title: 'The Executive Answer', objective: 'Deliver exact meaning with minimal words.', prompt: 'A senior client asks: "Should we delay the launch?" Answer in business-precise language, no hedging.', instructions: ['No "maybe", "kind of", "it depends" without a follow-up.', 'Your recommendation must be unmistakable.'], prepSeconds: 10, speakSeconds: 45 },
  { id: 'prec4', category: 'precision', tier: T.e, title: 'The Connoisseur', objective: 'Precise language under time pressure.', prompt: 'Explain the difference between confidence and arrogance in 45 seconds — with every word doing exact work.', instructions: ['No synonyms repeated.', 'Every sentence must survive cross-examination.'], prepSeconds: 5, speakSeconds: 45 },

  /* ---- fillers ---- */
  { id: 'fill1', category: 'fillers', tier: T.f, title: 'The Silent Gap', objective: 'Replace filler with deliberate pause.', prompt: 'Explain why most people avoid public speaking.', instructions: ['When you feel a filler coming, stop and breathe instead.', 'Silence is allowed. Filler is not.'], prepSeconds: 15, speakSeconds: 45 },
  { id: 'fill2', category: 'fillers', tier: T.d, title: 'The Clean Room', objective: 'Deliver a full answer with zero fillers.', prompt: 'Tell the listener what you would do with one completely free Saturday and why.', instructions: ['Any filler counts. The goal is a clean pass, not speed.', 'Pause as long as you need between sentences.'], prepSeconds: 15, speakSeconds: 45 },
  { id: 'fill3', category: 'fillers', tier: T.a, title: 'The Interrupted', objective: 'Hold fluency when the rhythm breaks.', prompt: 'Give your position on homework for schoolchildren. Every 15 seconds, the timer will demand one silent pause of two full seconds.', instructions: ['Use the pause to decide your next sentence.', 'Resume without any filler.'], prepSeconds: 10, speakSeconds: 60 },
  { id: 'fill4', category: 'fillers', tier: T.e, title: 'The Unfair Question', objective: 'Answer a hard question with unbroken composure.', prompt: 'Why should anyone trust your professional opinion over their own research?', instructions: ['No filler, no stalling.', 'Open with your strongest sentence.'], prepSeconds: 5, speakSeconds: 40 },

  /* ---- pace ---- */
  { id: 'pace1', category: 'pace', tier: T.f, title: 'The Metronome', objective: 'Find and hold your clarity pace.', prompt: 'Read out loud, then continue speaking: "Public speaking is a skill, not a gift." Explain what that means at a deliberately controlled pace.', instructions: ['Target roughly 140 words per minute.', 'Finish the ending of every word before starting the next.'], prepSeconds: 10, speakSeconds: 45 },
  { id: 'pace2', category: 'pace', tier: T.d, title: 'The Gear Change', objective: 'Move between speeds deliberately.', prompt: 'Describe a moment you were proud of. Tell it normally, then slow down for the most important sentence.', instructions: ['The important sentence should feel like it lands.', 'The listener should be able to identify it afterwards.'], prepSeconds: 15, speakSeconds: 60 },
  { id: 'pace3', category: 'pace', tier: T.a, title: 'Fast and Clear', objective: 'Speed without losing consonants.', prompt: 'Summarise a book or film you know well in 40 seconds — fast, but every word complete.', instructions: ['Speed is allowed. Blurring is not.', 'Word endings must survive.'], prepSeconds: 15, speakSeconds: 40 },
  { id: 'pace4', category: 'pace', tier: T.e, title: 'The Sprint Rewrite', objective: 'Say the same thing three ways at three speeds.', prompt: 'Answer: "What is the most underrated quality in a leader?" Give the answer three times — slow and heavy, then conversational, then fast.', instructions: ['The meaning must survive all three gears.', 'Each pass should be shorter than the last.'], prepSeconds: 15, speakSeconds: 75 },

  /* ---- articulation ---- */
  { id: 'art1', category: 'articulation', tier: T.f, title: 'The Endings', objective: 'Train word endings at natural speed.', prompt: 'Say and then use these words naturally in sentences: "grasped, judged, walked, laughed, demand, designed".', instructions: ['Do not slow down artificially.', 'Each final consonant must be audible.'], prepSeconds: 10, speakSeconds: 45 },
  { id: 'art2', category: 'articulation', tier: T.d, title: 'The Twister Pass', objective: 'Clean consonant clusters.', prompt: 'Say each phrase three times, then use it in a sentence: "strategic strength", "particular perspective", "regional restructuring".', instructions: ['Precision before speed.', 'Then speak normally and let the training carry.'], prepSeconds: 10, speakSeconds: 45 },
  { id: 'art3', category: 'articulation', tier: T.a, title: 'The Spontaneous Drift', objective: 'Articulation while improvising.', prompt: 'Speak for 60 seconds about whatever is in front of you right now — describe it, then argue why it matters.', instructions: ['Articulate as if being transcribed.', 'No mumbling between thoughts.'], prepSeconds: 5, speakSeconds: 60 },
  { id: 'art4', category: 'articulation', tier: T.e, title: 'The Accusation', objective: 'Clarity under emotional load.', prompt: 'Respond, out loud, to being blamed for something that was not your fault. Articulate the defence without letting heat reach your mouth.', instructions: ['Composure is the exercise.', 'Every word clean, even the angry ones.'], prepSeconds: 10, speakSeconds: 60 },

  /* ---- story ---- */
  { id: 'story1', category: 'story', tier: T.f, title: 'The Ninety-Second Story', objective: 'Tell a real story with a shape.', prompt: 'Tell a personal story about a time something went wrong and what it taught you.', instructions: ['Start inside the moment, not with background.', 'One story only. Land the lesson in one sentence.'], prepSeconds: 15, speakSeconds: 90 },
  { id: 'story2', category: 'story', tier: T.d, title: 'The Relevance Cut', objective: 'Only what serves the point survives.', prompt: 'Tell a story from your life that proves this: people change when they are trusted.', instructions: ['Cut every detail that does not serve the lesson.', 'Finish with the lesson stated plainly.'], prepSeconds: 20, speakSeconds: 90 },
  { id: 'story3', category: 'story', tier: T.a, title: 'The Stranger Story', objective: 'Make an abstract point land through a story.', prompt: 'Explain "compounding" — of money, skill or trust — through one story with no jargon.', instructions: ['The listener should feel the concept.', 'The word itself may appear once, at the end.'], prepSeconds: 20, speakSeconds: 90 },
  { id: 'story4', category: 'story', tier: T.e, title: 'The Cold Open', objective: 'Open a story so the listener cannot leave.', prompt: 'Begin a story with a sentence that forces attention, then earn the rest.', instructions: ['No "So, once upon a time".', 'The first sentence should be the hook, the last the point.'], prepSeconds: 10, speakSeconds: 90 },

  /* ---- persuasion ---- */
  { id: 'pers1', category: 'persuasion', tier: T.f, title: 'The Ask', objective: 'End a persuasion with an actual ask.', prompt: 'Persuade a busy person to spend 15 minutes a day reading.', instructions: ['Position → reason → example → ask.', 'The ask must be concrete.'], prepSeconds: 20, speakSeconds: 60 },
  { id: 'pers2', category: 'persuasion', tier: T.d, title: 'The Objection', objective: 'Meet the strongest objection head-on.', prompt: 'Convince an employer to allow fully remote work. Name their best objection yourself and answer it.', instructions: ['Do not dodge the objection.', 'Concede what is true, then win the point.'], prepSeconds: 20, speakSeconds: 75 },
  { id: 'pers3', category: 'persuasion', tier: T.a, title: 'The Enemy Frame', objective: 'Persuade without attacking.', prompt: 'Persuade someone who distrusts experts to trust a doctor\'s advice on vaccines.', instructions: ['No strawmen. No contempt.', 'Make agreeing feel like their idea.'], prepSeconds: 15, speakSeconds: 75 },
  { id: 'pers4', category: 'persuasion', tier: T.e, title: 'The Verdict', objective: 'Close like a courtroom.', prompt: 'You have 60 seconds to convince a panel of one change you would make to the education system. One change only.', instructions: ['Narrow the ask to a single, sharp change.', 'Close with the verdict sentence.'], prepSeconds: 10, speakSeconds: 60 },

  /* ---- pressure ---- */
  { id: 'press1', category: 'pressure', tier: T.f, title: 'The Ten-Second Window', objective: 'Think fast, speak slower.', prompt: 'You will be asked a question with ten seconds of silence first. Then answer: "Is it better to be respected or liked?"', instructions: ['Use the ten seconds to choose your point, not your words.', 'Open directly on the answer.'], prepSeconds: 10, speakSeconds: 45 },
  { id: 'press2', category: 'pressure', tier: T.d, title: 'The Ambush', objective: 'Answer without preparation.', prompt: 'Answer immediately: "What is the one belief you hold that most people disagree with?"', instructions: ['No stalling, no filler.', 'Commit to the answer.'], prepSeconds: 3, speakSeconds: 45 },
  { id: 'press3', category: 'pressure', tier: T.a, title: 'The Hostile Room', objective: 'Composure under challenge.', prompt: 'State an opinion you actually hold. Then spend the remaining time answering three challenges you pose to yourself, out loud.', instructions: ['Each challenge: state it, answer it, move on.', 'Composure is the exercise.'], prepSeconds: 5, speakSeconds: 90 },
  { id: 'press4', category: 'pressure', tier: T.e, title: 'The Elevator Reversal', objective: 'Change your position mid-answer and survive.', prompt: 'Begin arguing one side of "money buys happiness". Halfway through, reverse your position — and make the reversal feel like insight, not defeat.', instructions: ['The reversal must be earned with a reason.', 'Do not apologise for changing your mind.'], prepSeconds: 10, speakSeconds: 60 },

  /* ---- explain ---- */
  { id: 'exp1', category: 'explain', tier: T.f, title: 'The Child Explainer', objective: 'Make something complicated simple.', prompt: 'Explain how compound interest works to a ten-year-old.', instructions: ['One everyday analogy.', 'No jargon survives the first sentence.'], prepSeconds: 20, speakSeconds: 60 },
  { id: 'exp2', category: 'explain', tier: T.d, title: 'The Abstract-to-Concrete', objective: 'Ground an abstraction.', prompt: 'Explain what "culture" means in a company, using only concrete examples — no abstractions.', instructions: ['Every sentence must contain something the listener can see.', 'The word "culture" may appear once.'], prepSeconds: 20, speakSeconds: 75 },
  { id: 'exp3', category: 'explain', tier: T.a, title: 'The Technical Bridge', objective: 'Speak to two audiences at once.', prompt: 'Explain what an algorithm is — once for a child, once for an engineer — in the same answer.', instructions: ['Signpost the gear change.', 'Neither audience should feel abandoned.'], prepSeconds: 20, speakSeconds: 90 },
  { id: 'exp4', category: 'explain', tier: T.e, title: 'The One-Breath Summary', objective: 'Compress without losing meaning.', prompt: 'Summarise an entire industry or field you know in 30 seconds, with nothing lost that matters.', instructions: ['Choose what to cut — that is the exercise.', 'The summary must still be true.'], prepSeconds: 20, speakSeconds: 30 },

  /* ---- concise ---- */
  { id: 'con1', category: 'concise', tier: T.f, title: 'The Thirty-Second Answer', objective: 'Point-first discipline.', prompt: 'Answer in 30 seconds: "What is the biggest problem with how people communicate at work?"', instructions: ['Your point must arrive in the first 10 seconds.', 'Stop when you are done. Dead air is allowed.'], prepSeconds: 15, speakSeconds: 30 },
  { id: 'con2', category: 'concise', tier: T.d, title: 'The One-Sentence Takeaway', objective: 'End every answer with a takeaway sentence.', prompt: 'Give your view on social media and mental health, ending with one sentence someone could repeat to a friend.', instructions: ['The takeaway must be short, quotable and yours.', 'Nothing after it.'], prepSeconds: 15, speakSeconds: 45 },
  { id: 'con3', category: 'concise', tier: T.a, title: 'The Halfway Cut', objective: 'Finish before the timer does.', prompt: 'You have 60 seconds on this: "What makes advice useful?" Use 40 and stop deliberately.', instructions: ['Stop at 40 seconds with a full close.', 'The remaining 20 seconds are a test, not a gift.'], prepSeconds: 15, speakSeconds: 60 },
  { id: 'con4', category: 'concise', tier: T.e, title: 'The Twenty-Word Rule', objective: 'Maximum meaning, minimum material.', prompt: 'Answer "What do you stand for?" in no more than 20 seconds and about 50 words.', instructions: ['No word may be cut without loss.', 'Land it and stop.'], prepSeconds: 15, speakSeconds: 20 },

  /* ---- opinion ---- */
  { id: 'op1', category: 'opinion', tier: T.f, title: 'The Position', objective: 'State a position and hold it.', prompt: 'Should university education be free? Take a clear position and defend it.', instructions: ['Your position must be unmistakable in sentence one.', 'One reason, one example, close.'], prepSeconds: 15, speakSeconds: 60 },
  { id: 'op2', category: 'opinion', tier: T.d, title: 'The Steelman', objective: 'Argue the strongest version of what you oppose.', prompt: 'Argue for a position you personally disagree with, as persuasively as you can.', instructions: ['No caricature.', 'If it sounds weak, you have not tried.'], prepSeconds: 20, speakSeconds: 75 },
  { id: 'op3', category: 'opinion', tier: T.a, title: 'The Referee', objective: 'Judge fairly, conclude firmly.', prompt: 'Two colleagues each want a promotion. One is brilliant but difficult; the other is steady but unremarkable. Rule on who gets it, and why.', instructions: ['Acknowledge both sides briefly.', 'Then rule — no fence-sitting.'], prepSeconds: 20, speakSeconds: 75 },
  { id: 'op4', category: 'opinion', tier: T.e, title: 'The Non-Negotiable', objective: 'Hold a position while conceding honestly.', prompt: 'Defend: "The most important skill of the next decade is speaking well." Concede every fair point against you and still win.', instructions: ['Each concession must be real.', 'The position must survive them.'], prepSeconds: 15, speakSeconds: 90 },
];

/* The baseline assessment: a fixed sequence spanning the profile. */
export const BASELINE_CHALLENGES = [
  { id: 'base1', category: 'story', tier: T.f, title: 'Introduce Yourself', objective: 'A natural, memorable self-introduction.', prompt: 'Introduce yourself naturally, as if meeting someone important for the first time. Sixty seconds.', instructions: ['Who you are, what you do, what you care about.', 'Keep it natural, not rehearsed.'], prepSeconds: 15, speakSeconds: 60 },
  { id: 'base2', category: 'explain', tier: T.f, title: 'Simplify the Complicated', objective: 'Explain something complex, simply.', prompt: 'Explain something complicated that you understand well, as simply as possible.', instructions: ['Choose something real.', 'If a ten-year-old could not follow it, it is not simple enough.'], prepSeconds: 20, speakSeconds: 60 },
  { id: 'base3', category: 'opinion', tier: T.d, title: 'Defend a Position', objective: 'State an opinion and defend it.', prompt: 'Give your opinion on this and defend it: is it better to be a specialist or a generalist?', instructions: ['Take a clear side.', 'Anticipate the obvious counter and answer it.'], prepSeconds: 15, speakSeconds: 60 },
  { id: 'base4', category: 'story', tier: T.d, title: 'The Personal Story', objective: 'A shaped story, told well.', prompt: 'Tell a personal story in ninety seconds — a moment that changed how you think or act.', instructions: ['Start inside the moment.', 'Land the meaning in one closing sentence.'], prepSeconds: 20, speakSeconds: 90 },
  { id: 'base5', category: 'pressure', tier: T.d, title: 'The Unexpected Question', objective: 'Answer with almost no preparation.', prompt: 'Answer this with ten seconds of silence first: what is the most useful thing you believe that most people do not?', instructions: ['Use the silence to choose the point.', 'Then speak.'], prepSeconds: 10, speakSeconds: 60 },
  { id: 'base6', category: 'persuasion', tier: T.d, title: 'The Persuasion', objective: 'Move someone to act.', prompt: 'Persuade someone to start training their public speaking today. Make them act.', instructions: ['Position, reason, example, ask.', 'The ask must be concrete.'], prepSeconds: 15, speakSeconds: 60 },
  { id: 'base7', category: 'concise', tier: T.d, title: 'The Hard Question', objective: 'A difficult question, answered concisely.', prompt: 'In forty seconds: what is the one thing most people misunderstand about your field or work?', instructions: ['Answer the question actually asked.', 'Finish inside the time.'], prepSeconds: 15, speakSeconds: 40 },
];
